### ISSUE TITLE
Dropbox API v2

### ISSUE THREAD

**Issue by toddfreese** [danielbierwirth/DropboxBrowser#22]
Will this work with v2 of the Dropbox API?

**Comment by Sam-Spencer** [comment]
Looks like it is not currently working with version 2.0 of the API. However, I may look into pushing an update to the project if you're interested?

**Comment by toddfreese** [comment]
That would be great!

**Comment by Sam-Spencer** [comment]
Please see commit aceb89d756057fd827e484e55073817facac485a. The entire project has been refactored and upgraded. Everything now works with Dropbox API v2. 

Just be warned, at this time I haven't completely implemented all the features that were previously available in v5.1. There is no formal README documentation as of the moment. That being said, fairly good in-line documentation is available and explains what you need to get things running. Especially crucial is the 'applicationIsConfiguredForAuthorization' method.

Please let me know what you think of the refactored project! Anything you'd like to see added, changed, improved, removed before it's merged into master?

**Comment by toddfreese** [comment]
Is the master branch v6?

Also, seems like this is using #import <DropboxSDK/DropboxSDK.h> and the new SDK is #import <ObjectiveDropboxOffical/ObjectiveDropboxOffical.h> according to the Dropbox web site.

**Comment by Sam-Spencer** [comment]
@toddfreese Thanks for pointing out the issue. I'll take a look and get back to you soon.

And no, version 6.0 is currently only available on the feature branch.

**Comment by Sam-Spencer** [comment]
This issue should be fixed and will now be closed. Should there be further discussion or questions related to this issue, it can be reopened. Thank you.
