### ISSUE TITLE
Dropbox SDK v3.2?

### ISSUE THREAD

**Issue by toddfreese** [danielbierwirth/DropboxBrowser#29]
Can this project be used with v3.2 of the Dropbox SDK? The podspec wants an older version.

**Comment by Sam-Spencer** [comment]
Hmm... I haven't tested it yet, but I'll check it out and let you know if it works. If it does, you'll see an update out to the pod later today!

**Comment by toddfreese** [comment]
Any luck with this?

**Comment by Sam-Spencer** [comment]
Yes! Just updated the repo with the latest SDK and will be updating the pod spec in a minute here to reflect the changes...

**Comment by toddfreese** [comment]
So cocoapods keeps installing version 2.0.6 of the Dropbox SDK as a dependency instead of 3.2.0.

Analyzing dependencies
Downloading dependencies
Installing DropboxBrowser (6.0.1)
Installing ObjectiveDropboxOfficial 2.0.6 (was 3.2.0)

**Comment by Sam-Spencer** [comment]
Oops! Forgot to push up the updated podspec to the trunk 🙃! The [latest release is now available via Cocoa Pods](https://cocoapods.org/pods/DropboxBrowser). Be sure to update your pods and DropboxBrowser should jump to v6.1.2! Thanks for pointing this one out.
